version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo Build docker image
      - cd 0.X && docker build -t docker-image .