version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
  build:
    commands:
      - echo Build docker image
      - cd 0.X && docker build -t docker-image .