version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - echo Build docker image
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay& && cd 0.X && docker build -t docker-image .